### PR TITLE
fix: fix compilation with `test_only` feature

### PR DESCRIPTION
**Pull request by Nashtare**
address oversight from https://github.com/0xPolygonZero/zero-bin/pull/78

### CODE REVIEW

**Review by muursh — APPROVED** [review]

**Comment by Nashtare** [comment]
cc @muursh @cpubot I've added a distinct job to run the `simple_test.sh` script with `test_only` feature so that this doesn't happen anymore. Would need you to update the branch requirements to have these new jobs required (changed the name of the previous one for clarity).

**Review by 0xaatif — APPROVED** [review]
Thanks :)

**Comment by muursh** [comment]
> cc @muursh @cpubot I've added a distinct job to run the `simple_test.sh` script with `test_only` feature so that this doesn't happen anymore. Would need you to update the branch requirements to have these new jobs required (changed the name of the previous one for clarity).

Can you not do it? If not I'll work on you having access

**Comment by Nashtare** [comment]
I don't have access to `zero-bin`'s settings. Only `zk_evm`, not even `plonky2`.

**Pull request merged**
