### PR TITLE
Fixed proof gen debug script not forcing `1` worker

### PR DESCRIPTION
**Pull request by BGluth**
This was a fix made by @Nashtare on a testing branch, but it really should make it's way into `main`.

### CODE REVIEW

**Comment by muursh** [comment]
Do we want this straight into main?

**Comment by BGluth** [comment]
If you're ok with it then maybe we should. My original intent was to merge into `develop` but forgot to set the branch.

**Comment by muursh** [comment]
I think let's go into `develop`

**Review by muursh — APPROVED** [review]

**Review by Nashtare — COMMENTED** [review]
Actually I think we should enhance these testing scripts to support both sequential/parallel proving, and to support user provided logging. So that we can quickly test a block by passing "info" and proving/generating witness in parallel, or "trace" and sequential testing when actually debugging.

**Comment by muursh** [comment]
> Actually I think we should enhance these testing scripts to support both sequential/parallel proving, and to support user provided logging. So that we can quickly test a block by passing "info" and proving/generating witness in parallel, or "trace" and sequential testing when actually debugging.

Sounds sensible to me

**Pull request merged**
